### ISSUE TITLE
Documentation on how to configure rehype

### ISSUE THREAD

**Issue by schlichtanders** [adobe/remark-gridtables#8]
**Is your feature request related to a problem? Please describe.**
I would love to use GridTables in my markdown and mdx files within an astro static web-site setup. They work with unified/remark, hence I am so happy to have found this package.

When activating it, it indeed does something, but it does not show up as a table in the final html document.

This input
```md
+-------------------+------+
| Table Headings    | Here |
+--------+----------+------+
| Sub    | Headings | Too  |
+========+=================+
| cell   | column spanning |
| spans  +---------:+------+
| rows   |   normal | cell |
+---v----+:---------------:+
|        | cells can be    |
|        | *formatted*     |
|        | **paragraphs**  |
|        | ```             |
| multi  | and contain     |
| line   | blocks          |
| cells  | ```             |
+========+=========:+======+
| footer |    cells |      |
+--------+----------+------+
```

is rendered to
```html
<div>
    <div>
        <div>
            <div>
                <p>Table Headings</p>
            </div>
            <div>
                <p>Here</p>
            </div>
        </div>
        <div>
            <div>
                <p>Sub</p>
            </div>
            <div>
                <p>Headings</p>
            </div>
            <div>
                <p>Too</p>
            </div>
        </div>
    </div>
    <div>
        <div>
            <div>
                <p>cell
                    spans
                    rows</p>
            </div>
            <div>
                <p>column spanning</p>
            </div>
        </div>
        <div>
            <div>
                <p>normal</p>
            </div>
            <div>
                <p>cell</p>
            </div>
        </div>
        <div>
            <div>
                <p>multi
                    line
                    cells</p>
            </div>
            <div>
                <p>cells can be
                    <em>formatted</em>
                    <strong>paragraphs</strong>
                </p>
                <pre><code>and contain
blocks
</code></pre>
            </div>
        </div>
    </div>
    <div>
        <div>
            <div>
                <p>footer</p>
            </div>
            <div>
                <p>cells</p>
            </div>
            <div></div>
        </div>
    </div>
</div>
```

I am myself not a developer of remark/rehype and hence get stuck here. It would be great to be able to use gridtables as part of my standard markdown to html compilation process.

**Describe the solution you'd like**
It would help a lot if `remark-gridtables` could provide a simple example of how to configure remark-rehype or whatever needs to be configured in order to bring the gridtable to a table-like html output.

- One example which uses the html `table` tags would be very much appreciated so that gridtables can easily be used as a multiline alternative to standard markdown tables
- if the complex nested structure like in the example above cannot be translated to html `table`, it would be nice to have an example which translates it to a html table which uses the css grid or flex features.

**Describe alternatives you've considered**
I am a newbie here and have unfortunately no clues whether the unified/remark/rehype ecosystem has some other documentation on making such gridtables into nice looking html. Probably it has, but I don't know where to look.

**Additional context**
Thank you very very much for building this package! Having gridtables in my markdown workflow is a long standing wish.

**Comment by tripodsan** [comment]
good point... I'll add an example shortly...

**Comment by schlichtanders** [comment]
I can see a lovely html table now :)

thank you very much for your help
